version: "3.6"
services:
  core:
    image: javatest:latest
    ports:
      - 8080:8080
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
      - mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
